{
 "title": "YARA Email Scanner Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Malicious Email Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(rate({job=\"scanner\"} | json | level=\"WARNING\" [6h]))\r\n  /\r\n  (\r\n    sum(rate({job=\"scanner\"} | json | level=\"INFO\" |= \"successfully\" [6h])) +\r\n    sum(rate({job=\"scanner\"} | json | level=\"WARNING\" [6h]))\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Total quarantined emails",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"scanner\"} |= \"WARNING\" [6h]))"
    }
   ]
  },
  {
   "title": "Top 5 YARA Rules Triggered",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (yara_hit) (count_over_time({job=\"scanner\"} |= \"WARNING\" | json | line_format \"{{.yara_hit}}\" [6h])))"
    }
   ]
  },
  {
   "title": "Total clean emails",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"scanner\"} |= \"successfully\" [6h]))"
    }
   ]
  },
  {
   "title": "Quarantined Emails",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"scanner\"} | json | level=\"WARNING\" | line_format \"{{.sender}} → {{.recipient}}: {{.yara_hit}}\"\r\n"
    }
   ]
  }
 ]
}